"""device_family

Revision ID: 36d27b893107
Revises: c8bf566058a2
Create Date: 2026-09-23 10:10:47.482074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d27b893107'
down_revision: Union[str, Sequence[str], None] = 'c8bf566058a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_family', sa.String(length=32), server_default='simulation', nullable=False))
    op.create_index(op.f('ix_devices_device_family'), 'devices', ['device_family'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_device_family'), table_name='devices')
    op.drop_column('devices', 'device_family')
    # ### end Alembic commands ###
