"""sensor_readings_and_sampling

Revision ID: 9f3c8faa2b2b
Revises: 97019046a946
Create Date: 2026-09-30 10:30:31.112180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f3c8faa2b2b'
down_revision: Union[str, Sequence[str], None] = '97019046a946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_recorded', 'sensor_readings', ['device_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.add_column('devices', sa.Column('sampling_interval_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False))
    op.add_column('devices', sa.Column('tracking_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'tracking_enabled')
    op.drop_column('devices', 'sampling_interval_seconds')
    op.drop_index('ix_sensor_readings_device_recorded', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###
